name: Label New Issues

on:
  issues:
    types: [opened]

jobs:
  label-issues:
  runs-on: ubuntu-latest
  permissions: 
    issues: write
    contents: read

steps:
  - name: Checkout repository
    uses: actions/checkout@v1
  - name: Add Ready label
    env: 
      GH_Token: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      LABEL: "Ready"
    run: gh issue edit "$ISSUE_NUMBER" --add-label "$LABEL"
